name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Display triggered event
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        
      - name: Display runner OS
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        
      - name: Display branch and repository
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Display clone status
        run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        
      - name: Display workflow readiness
        run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Display job status
        run: echo "ğŸ This job's status is ${{ job.status }}."
